spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  redis:
    host: middleware.siupay.com # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 3087 # Redis服务器连接端口
    password: payment1234.... # Redis服务器连接密码（默认为空）
    timeout: 10000ms # 连接超时时间



#feign:
#  hystrix:
#    enabled: true
#  okhttp:
#    enabled: true

SERVER_IP: ${spring.cloud.client.ip-address}
server:
  port: ${SERVER_PORT:30000}
  ip: ${SERVER_IP}
  zone: ${ZONE:default}
  error:
    include-message: always

ribbon:
  eager-load:
    enabled: true
pa:
  internalapi:
    tokenservice:
      baseUrl: ${TOKEN_SERVICE_URI:http://PCI-TOKENSERVICE}

pci:
  dispatch:
    apiKey: ${PCI_DISPATCH_API_KEY:L2elxRoVqLSQ16GdtBIcUBIKPZL62Dzy}
    channelUri:
      checkout-auth: ${PCI_DISPATCH_API_URI_AUTH:https://api.sandbox.checkout.com/payments}
okhttp:
  client:
    readTimeout: ${OKHTTP_CLIENT_READ_TMEOUT:10}
    writeTimeout: ${OKHTTP_CLIENT_WRITE_TMEOUT:10}
    connectTimeout: ${OKHTTP_CLIENT_CONNECT_TMEOUT:10}
    maxIdleConnections: ${OKHTTP_CLIENT_MAX_IDLE_CONNECTIONS:50}
    keepAliveDuration: ${OKHTTP_CLIENT_KEEP_ALIVE_DURATION:120}
    proxySwitch: ${OKHTTP_CLIENT_PROXY_SWITCH:close}
    proxyIp: ${OKHTTP_CLIENT_PROXY_IP:10.70.28.133}
    proxyPort: ${OKHTTP_CLIENT_PROXY_PORY:9500}

logging:
  level:
    com.shopline.pc.gateway.tokenservice.client: 'info'
    org.springframework.web.client: 'off'
    org.springframework.web.HttpLogging: 'off'

apollo:
  meta: http://middleware.siupay.com:8080
  bootstrap:
    enabled: true
  config-service: http://middleware.siupay.com:8080


risk:
  decrypt:
    key: "6OKyDIJGv8vBQkGUUfL5Yo9iB89L9YESLDDciKq2GIo="

access:
  limit:
    times: 1
    seconds: 10
    bindCardTimes: 10
    bindCardSeconds: 86400

bind:
  card:
    rsaPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDCInYu66Ww7u0zvpoqoRqfk9J4Ai/rWFrzyI/ElhGrN7kSOWdpUjA9fdZllygmb77bidKJW4mP15MgFufWI+N+MMjekuHEm3ikQZWWIckVS4RDbInexraYpIwgXe1WnzgF8E8FlZpr7XqMHiXmqe6t7S6BY1fbw0NRhH6rAG5MpQIDAQAB
    rsaPrivateKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAMIidi7rpbDu7TO+miqhGp+T0ngCL+tYWvPIj8SWEas3uRI5Z2lSMD191mWXKCZvvtuJ0olbiY/XkyAW59Yj434wyN6S4cSbeKRBlZYhyRVLhENsid7GtpikjCBd7VafOAXwTwWVmmvteoweJeap7q3tLoFjV9vDQ1GEfqsAbkylAgMBAAECgYEArqe0bdghlEIQc3oqVunj+udR9hf5pqEyCptJBNMCiGi0fznX2IBR2DCrP3CzdYkZS4f+Owd4hkmrGrag0x4snpzBQYRi8X5eCAKM+2o+Rob2wdcDQnzx6tkDlKoS8pwaNazNPSW8nP0Ru6XafwpV2UcC0TumFgUP5e8IzUZSD40CQQDm+M2e7G98vrAmu3Dl9oqwht4hpR6NmZhfYusSPXWyIrL3XJJWRb8LIJ+ZUEWKcfsXUJm0ZWpKcfV83ESxfkGfAkEA1yvJZGAmuvYamx1moTOii501BVURbqaiZS9DGq/CJ7mjXtitWsFEKhaslj6kU/jOyxBaGQ5jjAbKVJ70iK2zOwI/Uhoe/V8OQkmGVD5M43G/2wAV9d+7/JmckEuZQ+KU871h4IwHeKNSRaJTGSxvi8b4elEsUfO61Luth7TEtlMrAkAvhxB5B3QGoA3IbXoZ6VniFNt9TgkHs+7zArmDz4bHV43qiVnhTgdMdK2ykiuiELc8y2PbXP5IE8flYScKebO5AkEAvkD/N4zdhyuRwGKOSCDs/sehOGOqYXBvaerELd3Bev3z24ZM8rVblEqmEIamE/pUhv2yQGOm9fyk71+If6iziQ==
    switch: "OFF"
    overDueTimeMillis: 12000
